feat: initial setup of tension module in pypilecore
cemsbv/py-pilecore pull request #103
Opened 2024-10-14 09:44 UTC by RDWimmers

2024-11-05 10:35 UTC, tlukkezen requested changes

2024-11-05 12:11 UTC, tlukkezen commented on src/pypilecore/results/result_definitions.py
> +    R_t_d_min = ResultDefinition(
Or maybe check the docstrings?

2025-01-03 12:49 UTC, RDWimmers commented on src/pypilecore/results/result_definitions.py
> +    R_t_d_mean = ResultDefinition(
for tension all parameters are design or characteristic. qc -> qc_char or qc_d

2025-01-03 12:49 UTC, RDWimmers commented on src/pypilecore/input/soil_properties.py
> +    individual_top_of_tension_zone_nap: Mapping[Any, float] | None = None,
for tension all parameters are design or characteristic. qc -> qc_char or qc_d

2025-01-03 12:49 UTC, RDWimmers commented on src/pypilecore/results/result_definitions.py
> +    R_t_d_min = ResultDefinition(
for tension all parameters are design or characteristic. qc -> qc_char or qc_d

2025-01-03 12:50 UTC, RDWimmers commented on src/pypilecore/results/tension_single_cpt_results.py
> +class CPTResultsTable:
created type classes for Protocol approach

2025-01-13 08:38 UTC, tlukkezen commented on src/pypilecore/results/typing.py
> +S = TypeVar("S", CPTCompressionGroupResultsTable, CPTTensionGroupResultsTable)
These classes also have similar methods, so you could also make a Protocol for them

2025-02-14 10:39 UTC, merged